
version: '3'


services:
  db:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: market
    volumes:
      - ./postgres:/var/lib/postgresql/data